import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Providers } from "@/redux/Providers";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "TODO APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased vsc-initialized`}>
        <Providers>
          <Theme>{children}</Theme>
        </Providers>
      </body>
    </html>
  );
}
