import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/redux/Providers";

export const metadata: Metadata = {
  title: "TODO APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased vsc-initialized`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
